name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: "MANIFEST_URL"
        required: true
        default: "https://github.com/PitchBlackRecoveryProject/manifest_pb"
      MANIFEST_BRANCH:
        description: "MANIFEST_BRANCH"
        required: true
        default: "android-12.1"
      DEVICE_TREE_URL:
        description: "DEVICE_TREE_URL"
        required: true
        default: "https://github.com/scas-projects/device_xiaomi_spes-pbrp"
      DEVICE_TREE_BRANCH:
        description: "DEVICE_TREE_BRANCH"
        required: true
        default: "android-12.1"
      DEVICE_PATH:
        description: "DEVICE_PATH"
        required: true
        default: "device/xiaomi/spes"
      DEVICE_NAME:
        description: "DEVICE_NAME"
        required: true
        default: "spes"
      MAKEFILE_NAME:
        description: "MAKEFILE_NAME"
        required: true
        default: "omni_spes"
      BUILD_TARGET:
        description: "BUILD_TARGET"
        required: true
        default: "boot"

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Display Run Parameters
        run: |
          echo "::group::User Environment Variables"
          echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
          echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
          echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
          echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
          echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
          echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
          echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
          echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
          echo "::endgroup::"

      # You might want to Checkout your repo first, but not mandatory
      - name: Check Out
        uses: actions/checkout@v3

      - name: Download file
        run: curl -LJO https://github.com/sakshiagrwal/PayloadActions/releases/download/3918118713/boot.img

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: boot.img
          name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            **Device:** ${{ github.event.inputs.DEVICE_NAME }}

            **Target:** ${{ github.event.inputs.BUILD_TARGET }}.img

            **Device Tree:** [URL](${{ github.event.inputs.DEVICE_TREE_URL }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})

            **Manifest:** [URL](${{ github.event.inputs.MANIFEST_URL }}/tree/${{ github.event.inputs.MANIFEST_BRANCH }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
